//
//  ARMCRC32C.swift
//  CRC32C
//
//  Created by Charles Srstka on 1/20/25.
//

// Based on code generated by https://github.com/corsix/fast-crc32/ using:
// ./generate -i neon_eor3 -p crc32c -a v9s3x2e_s3
// MIT licensed

import _Builtin_intrinsics.arm.acle
import _Builtin_intrinsics.arm.neon
import asm

public struct CorsixARMCRC32C {
    private static func xnmodp(_ _n: UInt64) -> UInt32 {
        // x^n mod P, in log(n) time

        var stack: UInt64 = ~1
        var n = _n

        while n > 191 {
            stack = (stack &<< 1) &+ (n & 1)
            n = (n &>> 1) &- 16
        }

        stack = ~stack
        var acc: UInt32 = 0x80000000 &>> (n & 31)

        for _ in 0..<(n &>> 5) {
            acc = __crc32cw(acc, 0)
        }

        while true {
            let low = stack & 1
            stack &>>= 1

            if stack == 0 { break }

            let x = vreinterpret_p8_p64(vmov_n_u64(UInt64(acc)))
            let y = vreinterpretq_u64_p16(vmull_p8(x, x)).x
            acc = __crc32cd(0, y &<< low)
        }

        return acc
    }

    @inline(__always)
    private static func crc_shift(_ crc: UInt32, _ nbytes: UInt64) -> SIMD2<UInt64> {
        clmul_scalar(crc, xnmodp(nbytes &* 8 &- 33))
    }

    public static func crc32c(bytes: UnsafeRawBufferPointer, initialValue: UInt32) -> UInt32 {
        guard let baseAddress = bytes.baseAddress else { return initialValue }

        var crc0 = ~initialValue
        let aligned = baseAddress.alignedUp(for: UInt64.self)

        let toAlign = min(aligned - baseAddress, bytes.count)
        for byte in bytes.prefix(toAlign) {
            crc0 = __crc32cb(crc0, byte)
        }

        var quads = bytes[toAlign...].bindMemory(to: UInt64.self)

        if quads.count >= 24 {
            let blk = quads.count / 24
            let klen = blk &* 2

            let endOffset = quads[(klen * 3)...].withMemoryRebound(to: SIMD2<UInt64>.self) { vecs in
                var quadsPtr = quads.baseAddress!
                var vecsPtr = vecs.baseAddress!
                let limit = quadsPtr + klen - 4

                // First vector chunk.
                var x0 = vecsPtr.pointee
                var x1 = (vecsPtr + 1).pointee
                var x2 = (vecsPtr + 2).pointee
                var x3 = (vecsPtr + 3).pointee
                var x4 = (vecsPtr + 4).pointee
                var x5 = (vecsPtr + 5).pointee
                var x6 = (vecsPtr + 6).pointee
                var x7 = (vecsPtr + 7).pointee
                var x8 = (vecsPtr + 8).pointee

                var y0, y1, y2, y3, y4, y5, y6, y7, y8: SIMD2<UInt64>

                var k = SIMD2<UInt64>(0x7e908048, 0xc96cfdc0)
                vecsPtr += 9

                var crc1: UInt32 = 0
                var crc2: UInt32 = 0

                // Main loop.
                while quadsPtr <= limit {
                    y0 = clmul_lo(x0, k); x0 = clmul_hi(x0, k)
                    y1 = clmul_lo(x1, k); x1 = clmul_hi(x1, k)
                    y2 = clmul_lo(x2, k); x2 = clmul_hi(x2, k)
                    y3 = clmul_lo(x3, k); x3 = clmul_hi(x3, k)
                    y4 = clmul_lo(x4, k); x4 = clmul_hi(x4, k)
                    y5 = clmul_lo(x5, k); x5 = clmul_hi(x5, k)
                    y6 = clmul_lo(x6, k); x6 = clmul_hi(x6, k)
                    y7 = clmul_lo(x7, k); x7 = clmul_hi(x7, k)
                    y8 = clmul_lo(x8, k); x8 = clmul_hi(x8, k)

                    x0 = eor3(x0, y0, vecsPtr.pointee)
                    x1 = eor3(x1, y1, (vecsPtr + 1).pointee)
                    x2 = eor3(x2, y2, (vecsPtr + 2).pointee)
                    x3 = eor3(x3, y3, (vecsPtr + 3).pointee)
                    x4 = eor3(x4, y4, (vecsPtr + 4).pointee)
                    x5 = eor3(x5, y5, (vecsPtr + 5).pointee)
                    x6 = eor3(x6, y6, (vecsPtr + 6).pointee)
                    x7 = eor3(x7, y7, (vecsPtr + 7).pointee)
                    x8 = eor3(x8, y8, (vecsPtr + 8).pointee)

                    crc0 = __crc32cd(crc0, quadsPtr.pointee)
                    crc1 = __crc32cd(crc1, (quadsPtr + klen).pointee)
                    crc2 = __crc32cd(crc2, (quadsPtr + klen * 2).pointee)
                    crc0 = __crc32cd(crc0, (quadsPtr + 1).pointee)
                    crc1 = __crc32cd(crc1, (quadsPtr + klen + 1).pointee)
                    crc2 = __crc32cd(crc2, (quadsPtr + klen * 2 + 1).pointee)

                    quadsPtr += 2
                    vecsPtr += 9
                }

                // Reduce x0 ... x8 to just x0.
                k = SIMD2<UInt64>(0xf20c0dfe, 0x493c7d27)
                y0 = clmul_lo(x0, k); x0 = clmul_hi(x0, k)
                x0 = eor3(x0, y0, x1)
                x1 = x2; x2 = x3; x3 = x4; x4 = x5; x5 = x6; x6 = x7; x7 = x8
                y0 = clmul_lo(x0, k); x0 = clmul_hi(x0, k)
                y2 = clmul_lo(x2, k); x2 = clmul_hi(x2, k)
                y4 = clmul_lo(x4, k); x4 = clmul_hi(x4, k)
                y6 = clmul_lo(x6, k); x6 = clmul_hi(x6, k)
                x0 = eor3(x0, y0, x1)
                x2 = eor3(x2, y2, x3)
                x4 = eor3(x4, y4, x5)
                x6 = eor3(x6, y6, x7)

                k = SIMD2<UInt64>(0x3da6d0cb, 0xba4fc28e)
                y0 = clmul_lo(x0, k); x0 = clmul_hi(x0, k)
                y4 = clmul_lo(x4, k); x4 = clmul_hi(x4, k)
                x0 = eor3(x0, y0, x2)
                x4 = eor3(x4, y4, x6)

                k = SIMD2<UInt64>(0x740eef02, 0x9e4addf8)
                y0 = clmul_lo(x0, k); x0 = clmul_hi(x0, k)
                x0 = eor3(x0, y0, x4)

                // Final scalar chunk.
                crc0 = __crc32cd(crc0, quadsPtr.pointee)
                crc1 = __crc32cd(crc1, (quadsPtr + klen).pointee)
                crc2 = __crc32cd(crc2, (quadsPtr + klen * 2).pointee)
                crc0 = __crc32cd(crc0, (quadsPtr + 1).pointee)
                crc1 = __crc32cd(crc1, (quadsPtr + klen + 1).pointee)
                crc2 = __crc32cd(crc2, (quadsPtr + klen * 2 + 1).pointee)

                let vc0 = crc_shift(crc0, UInt64(klen) * 16 + UInt64(blk) * 144)
                let vc1 = crc_shift(crc1, UInt64(klen) * 8 + UInt64(blk) * 144)
                let vc2 = crc_shift(crc2, UInt64(blk) * 144)
                let vc = eor3(vc0, vc1, vc2).x
                // Reduce 128 bits to 32 bits, and multiply by x^32.
                crc0 = __crc32cd(0, x0.x)
                crc0 = __crc32cd(crc0, vc ^ x0.y)

                return Int(bitPattern: vecsPtr) - Int(bitPattern: baseAddress)
            }

            quads = bytes[endOffset...].bindMemory(to: UInt64.self)
        }

        if quads.count >= 4 {
            let klen = (quads.count &- 1) / 3
            let triples = zip(quads[..<klen], zip(quads[klen..<(klen &* 2)], quads[(klen &* 2)...]))

            var crc1: UInt32 = 0
            var crc2: UInt32 = 0

            // Main loop.
            for (q0, (q1, q2)) in triples {
                crc0 = __crc32cd(crc0, q0)
                crc1 = __crc32cd(crc1, q1)
                crc2 = __crc32cd(crc2, q2)
            }

            let vc0 = crc_shift(crc0, (UInt64(klen) &* 2 &+ 1) &* 8)
            let vc1 = crc_shift(crc1, (UInt64(klen) &+ 1) &* 8)
            let vc = veorq_u64(vc0, vc1).x

            // Final 8 bytes.
            crc0 = __crc32cd(crc2, quads[(klen &* 3)] ^ vc)

            quads = UnsafeBufferPointer(rebasing: quads[((klen &* 3) &+ 1)...])
        }

        for quad in quads {
            crc0 = __crc32cd(crc0, quad)
        }

        for byte in bytes.suffix((bytes.count - toAlign) % 8) {
            crc0 = __crc32cb(crc0, byte)
        }

        return ~crc0
    }
}
