name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm]
        traits: ["all", "none", "Foundation", "ZLib", "Crypto"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - name: Determine traits flags
      id: traits
      run: |
        if [[ ${{ matrix.traits }} = 'all' ]]; then
          echo "flags=--enable-all-traits" >> $GITHUB_OUTPUT
        elif [[ ${{ matrix.traits }} = 'none' ]]; then
          echo "flags=--disable-default-traits" >> $GITHUB_OUTPUT
        else
          echo "flags=--traits ${{ matrix.traits }}" >> $GITHUB_OUTPUT
        fi
    - name: Build
      run: swift build -v ${{ steps.traits.outputs.flags }}
    - name: Run tests
      run: swift test -v ${{ steps.traits.outputs.flags }}
