name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, macos-15-intel, ubuntu-latest, ubuntu-24.04-arm]
        traits: ["all", "none", "Foundation", "ZLib", "Crypto"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - name: Run tests
      run: |
        if [[ ${{ matrix.traits }} = 'all' ]]; then
          swift test -v --enable-all-traits
        elif [[ ${{ matrix.traits }} = 'none' ]]; then
          swift test -v --disable-default-traits
        else
          swift test -v --traits ${{ matrix.traits }}
        fi
